############################################################
#
# Spring Configuration
#
############################################################
spring:
  main:
    web-application-type: NONE
  datasource:
    type: com.zaxxer.hikari.HikariDataSource   # HikariCP connection pool
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wordbook?characterEncoding=utf-8
    username: user
    password: 12345678
    hikari:
      connection-timeout: 30000       # ???????????????????????????????????SQLException? ??:30?
      minimum-idle: 5                 # ?????
      maximum-pool-size: 50           # ?????
      auto-commit: true               # ????
      idle-timeout: 600000            # ?????????????????????retired????:10??
      pool-name: HikariCP     # ?????
      max-lifetime: 1800000           # ?????????????????????????retired????:30?? 1800000ms
      connection-test-query: SELECT 1

############################################################
#
# mybatis
#
############################################################
mybatis:
  type-aliases-package: cn.edu.jit.wdnv.java.wordbook.model         # define pojo class path
  mapper-locations: classpath:cn/edu/jit/wdnv/java/wordbook/mapper/*.java      # mapper path
#showSql
logging:
  level:
    cn:
      edu:
        jit:
          wdnv:
            wordbook:
              mapper: DEBUG